version: '3.3'

services:
  app:
    image: docker.io/fireflyiii/core:latest
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db
  db:
    image: docker.io/mariadb    
    hostname: fireflyiiidb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    ports:
      - 3306:3306
  mail:
    image: docker.io/bytemark/smtp
    restart: unless-stopped
    ports:
      - '3025:25'
volumes:
   firefly_iii_upload:
   firefly_iii_db:
